name: build

on:
  pull_request:
    branches: [main, development]

# Test if Wase-ECS is buildable on various environments and run tests
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      shell: cmd
      run: |
        mkdir build && cd build
        cmake .. -Denable_test=1
        cmake --build .
    - name: tests
      shell: cmd
      run: cd build/tests && ctest

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      shell: bash
      run: |
        mkdir build && cd build
        cmake .. -Denable_test=1
        cmake --build .
    - name: tests
      shell: bash
      run: cd build/tests && ctest

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      shell: bash
      run: |
        mkdir build && cd build
        cmake .. -Denable_test=1
        cmake --build .
    - name: tests
      shell: bash
      run: cd build/tests && ctest
